### ISSUE TITLE
Improve scrolling performance 

### ISSUE THREAD

**Issue by DougRogers** [DougRogers/Tinta#12]
The scroll rate and thumbnail refresh rate could be better.

**Comment by RandyHaylor** [comment]
It's a little sluggish on my machine as well (2600k i7, 980ti)

I instinctively put my photo vault folder on my large spinning drive when I set up.

Are the two DriveIndex files important for performance? They're about 26mb each and currently on my spinning hdd inside the photo vault folder.  Could it be better to have them on a ssd or in the user folder?  I've been testing by selecting my c: ssd on opening, so it's showing images on a mid grade samsung sata ssd.

**Comment by DougRogers** [comment]
Drive index files are used to store the drive data, so a full scan is not needed on subsequent runs.   They are read at startup and written at shutdown, but not used during runtime.  Putting them on an SSD is preferred, but will only affect startup/shutdown time.  They are located in the 'vault' that was specified the first time Tinta was run.

**Comment by DougRogers** [comment]
Setting the lookahead value will affect scrolling performance.  A significant effort in this project is to get a very large number of thumbnails to scroll fast in Qt.

**Comment by RandyHaylor** [comment]
I have experimented with different lookahead values (very low and very high). Not super smooth but usable at 100 ish on my system (which is older).
Would it be feasible to generate low res thumbnails for everything permanently and build the view up with them first? Blurry placeholders would load fast, allow the ui to space itself properly, and even be pretty useful in fast scrolling. The high res could load independent somehow of the scrolling experience perhaps.
    On Friday, October 28, 2022 at 09:56:34 AM EDT, DougRogers ***@***.***> wrote:  
 
 


Setting the lookahead value will affect scrolling performance. A significant effort in this project is to get a very large number of thumbnails to scroll fast in Qt.

**Comment by DougRogers** [comment]
@RandyHaylor I initially implemented a preprocessing step to build all the thumbnails, then load them into Tinta as needed.  After several hours of thumbnail generation on all my disks, I abandoned that idea.  Some formats, like TIFF, take a long time to read, even to generate a thumbnail.

I did realize that the way I was saving the generated thumbnail could be better.  Up to this point, I was saving the thumbnails in a .bmp file after being generated.  I changed the approach in version 0.9.43, which I just submitted to the MS store.  I am now saving the thumbnails to memory and storing them in the drive index file.

Before you install 0.9.43, start Tinta, open the maintenance dialog and delete the thumbnails.  It is not required, but it will remove unneeded thumbnail files.

Alternatively, you can delete this directory.  It is probably a hidden dir.
C:\Users\<USERNAME>\AppData\Roaming\Tinta\Thumbnails

0.9.43 should be posted soon.

I am looking to get the scrolling super smooth.

**Comment by DougRogers** [comment]
I changed the way drive indexing works (in 0.9.44) while working on this.  Please delete your drive index files before running 0.9.44

You can delete them from the vault or through the maintenance dialog.

**Comment by RandyHaylor** [comment]
Interestingly, the AppData directory did not exist for me:C:\Users<USERNAME>\AppData\Roaming\Tinta\Thumbnails

I looked around, including giving myself ownership of my windowsApps Folder and looking through the app's folder (also I just searched my drives)
The only other location I could find anything was the photo vault folder I specified on my first install of the app (contained the two index files).
I have hidden files shown, pretty confident at my poking-around-for-stuff ability in windows.
Where else could the thumbnails have been stored?  Could they possibly not have been stored at all due to some issue?

    On Friday, October 28, 2022 at 04:52:08 PM EDT, DougRogers ***@***.***> wrote:  
 
 


@RandyHaylor I initially implemented a preprocessing step to build all the thumbnails, then load them into Tinta as needed. After several hours of thumbnail generation on all my disks, I abandoned that idea. Some formats, like TIFF, take a long time to read, even to generate a thumbnail.

I did realize that the way I was saving the generated thumbnail could be better. Up to this point, I was saving the thumbnails in a .bmp file after being generated. I changed the approach in version 0.9.43, which I just submitted to the MS store. I am now saving the thumbnails to memory and storing them in the drive index file.

Before you install 0.9.43, start Tinta, open the maintenance dialog and delete the thumbnails. It is not required, but it will remove unneeded thumbnail files.

Alternatively, you can delete this directory. It is probably a hidden dir.
C:\Users<USERNAME>\AppData\Roaming\Tinta\Thumbnails

0.9.43 should be posted soon.

I am looking to get the scrolling super smooth.

**Comment by RandyHaylor** [comment]
Deleted drive index files, updated app, opened normally first try.
Seemed similar, had some choppiness with 100 thumbnails (my existing setting from before).
Lowered to 30, tried scrolling around. Seemed smoother, then crashed (no prompt to send info)


Opened again, changed to 30 thumbnails again (it had reverted to 100), scrolled through about 5 pages worth of images, crashed again in same way:

Next try, didn't try to change thumbnail setting, app crashed after a couple pages of scrolling but did ask to send debug data (I clicked send).


Next try, crashed as the initial times without changing settings after scrolling through a few pages.


Tried a couple more times and last time it asked to upload crash data again.  I had scrolled a bunch the last time, looked at my phone for a few minutes, then it had crashed when I looked back.







    On Friday, October 28, 2022 at 09:55:35 PM EDT, DougRogers ***@***.***> wrote:  
 
 


I changed the way drive indexing works (in 0.9.44) while working on this. Please delete your drive index files before running 0.9.44

You can delete them from the vault or through the maintenance dialog.

**Comment by DougRogers** [comment]
Tinta should work without having the files saved.  It would just rebuild the thumbnails if needed.  
If they are on your system, you should be able to locate the thumbnails with the "Everything" tool, available [here](https://www.voidtools.com/).

Try searching for "Tinta" and set "Search->Match Whole Word" to true

**Comment by DougRogers** [comment]
Those crashes both occurred in the lookahead.  That crash issue should be resolved with 0.9.44.  If not please file a separate issue.

**Comment by DougRogers** [comment]
I think I need to use a background task that scans the disk and builds thumbnails in a background task.  That way, when a thumbnail is requested, it may have already been created.

I think that is what Picasa does.

**Comment by DougRogers** [comment]
0.9.46.0 was just posted.  This build should have some noticeable scrolling improvement.

**Comment by DougRogers** [comment]
0.9.47.0 was just posted. 

Several performance changes for scrolling and thumbnail generation.
   Background thumbnail reader.
   Better parallel loading of thumbnails
   Better database sheduling
   Button to create all thumbnails at once

**Comment by DougRogers** [comment]
0.9.48.0 was just posted.  Even more improvements to scrolling and thumbnail loading.  I'm much happier with this version.

**Comment by DougRogers** [comment]
Closing this issue for now.  There is very little overhead now and is limited by the Qt QListView class.
